### ISSUE TITLE
Event Triggers (create,change,delete) not working.

### ISSUE THREAD

**Issue by parkesdesign** [CiviCooP/org.civicoop.civirules#90] opened 2016-07-01 09:57 UTC
The below tests were done on clean installs of CiviCRM 4.6.18 and 4.7.8
1. Download and install the latest master version of CiviRules via github.
2. Create a rule with trigger new event.
3. Create a new event, click save and the below error message occurs.

Sorry but we are not able to provide this at the moment.
One of parameters (value: ) is not of the type Integer
1. Go to CiviRules and disable rule.
2. Create a new event, click save and event is created.

The scenario is the same when the trigger is edit and delete event.

Further information - Drupal 7.44, PHP 5.6.22, mysql 5.5.49

backtrace error is below:

```
#0 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Error.php(360): CRM_Core_Error::backtrace()
#1 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Type.php(415): CRM_Core_Error::fatal("One of parameters  (value: ) is not of the type Integer")
#2 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/DAO.php(1251): CRM_Utils_Type::validate(NULL, "Integer")
#3 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/DAO.php(1168): CRM_Core_DAO::composeQuery("INSERT INTO `civirule_rule_log` (`rule_id`, `contact_id`, `log_date`) VALUES ...", (Array:2), TRUE)
#4 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Engine.php(285): CRM_Core_DAO::executeQuery("INSERT INTO `civirule_rule_log` (`rule_id`, `contact_id`, `log_date`) VALUES ...", (Array:2))
#5 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Engine.php(30): CRM_Civirules_Engine::logRule(Object(CRM_Civirules_TriggerData_Post))
#6 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Trigger/Post.php(81): CRM_Civirules_Engine::triggerRule(Object(CRM_Civirules_Trigger_Post), Object(CRM_Civirules_TriggerData_Post))
#7 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Trigger/Post.php(66): CRM_Civirules_Trigger_Post->triggerTrigger("create", "Event", 12, Object(CRM_Event_DAO_Event))
#8 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/civirules.php(137): CRM_Civirules_Trigger_Post::post("create", "Event", 12, Object(CRM_Event_DAO_Event))
#9 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Hook.php(213): civirules_civicrm_post("create", "Event", 12, Object(CRM_Event_DAO_Event))
#10 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(87): CRM_Utils_Hook->runHooks((Array:33), "civicrm_post", 4, "create", "Event", 12, Object(CRM_Event_DAO_Event), NULL, NULL)
#11 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Hook.php(304): CRM_Utils_Hook_DrupalBase->invoke(4, "create", "Event", 12, Object(CRM_Event_DAO_Event), NULL, NULL, "civicrm_post")
#12 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Event/BAO/Event.php(110): CRM_Utils_Hook::post("create", "Event", 12, Object(CRM_Event_DAO_Event))
#13 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Event/BAO/Event.php(141): CRM_Event_BAO_Event::add((Array:28))
#14 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Event/Form/ManageEvent/EventInfo.php(307): CRM_Event_BAO_Event::create((Array:28))
#15 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Event_Form_ManageEvent_EventInfo->postProcess()
#16 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(166): CRM_Core_Form->mainProcess()
#17 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(133): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Event_Form_ManageEvent_EventInfo), "upload")
#18 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Event_Form_ManageEvent_EventInfo), "upload")
#19 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_ManageEvent_EventInfo), "upload")
#20 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("upload")
#21 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(115): CRM_Core_Controller->run()
#22 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(286): CRM_Utils_Wrapper->run("CRM_Event_Form_ManageEvent_EventInfo", "New Event", NULL)
#23 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:15))
#24 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#25 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#26 [internal function](): civicrm_invoke("event", "add")
#27 /var/www/clients/client1/web8/web/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#28 /var/www/clients/client1/web8/web/index.php(21): menu_execute_active_handler()
#29 {main}
```

**Comment by parkesdesign** [comment] 2016-07-01 10:01
@jaapjansma I appreciate the time and effort civicoop has put into developing and sharing this extension, are you able to point me into any direction as to how I can try to debug this? searching documentation online points to how to create custom conditions not triggers or is this more of a wishlist fix?

**Comment by ErikHommel** [comment] 2016-07-01 13:09
@parkesdesign  have answered your StackExchange question with a pointer? The engine we designed allows for the creation of conditions and actions only. The triggers depend on the hooks civicrm_pre and civicrm_post with a known CiviCRM entity so that is bit more complex. If you do create your own entities in your extension you could certainly add a trigger but it is certainly something for the experienced CiviCRM developer :-)

**Comment by jaapjansma** [comment] 2016-07-01 13:13
I do think that this issue is caused by the fact the Event object has no related contact. And the engine expects that a related contact is filled in. We could work around this, we have done so with Relationship (which holds two contacts), Cases, which holds multiple contacts, Activities which holds a target contacts, assignees etc...

**Comment by gah242s** [comment] 2016-07-01 14:14
I believe that this issue should replace issue 79:  https://github.com/CiviCooP/org.civicoop.civirules/issues/79

**Comment by eileenmcnaughton** [comment] 2016-07-11 04:21
Hey - you need to add an entityTypes hook - see

https://github.com/eileenmcnaughton/nz.co.fuzion.entitysetting/blob/master/entitysetting.php#L286

**Comment by jaapjansma** [comment] 2016-07-11 07:24
@eileenmcnaughton how does the entityType hook works? And how does that fix the problem of the trigger not working on the Event entity? And what about CiviCRM version 4.6?

**Comment by eileenmcnaughton** [comment] 2016-07-11 07:39
I'm not fully clear on the history - but I know it has been causing problems in extensions that don't have the hook since 4.7 came out & now the api code is almost the same in 4.6 it causes problems there too.

I don't know for sure this extension will have problems - but I've seen them in others (it was what CiviVolunteer had to fix to provide 4.7 support )

https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_entityTypes

**Comment by jaapjansma** [comment] 2016-07-11 07:42
@eileenmcnaughton thanks for sharing. I do think the problem is here that we use the post_hook on the Event entity and we haven't implemented that one in Civirules yet and it is failing because the Event entity does not have a related a contact (E.g. participant has a related contact, so does contributions etc...)

**Comment by gah242s** [comment] 2016-07-11 15:09
Hrm ... Either this didn't work, or I've got something broke on my dev box.  (Which I do, but not sure it would stop this.  Uninstalling the INNODB log extension still leaves the same error on subsequent database upgrades.  But that's a side issue I'll add over there.)

**Comment by jaapjansma** [comment] 2018-06-12 07:55
I have tested this one and the error seems to be gone. I have also checked the code and can't see how this one would happen. Therefor I will close this issue.

**Closed by jaapjansma** 2018-06-12 07:55 UTC
