### ISSUE TITLE
Civirules preventing creation of new custom fields

### ISSUE THREAD

**Issue by elijahv** [CiviCooP/org.civicoop.civirules#132] opened 2017-02-06 19:43 UTC
Civirules 1.2 is preventing me from successfully creating a custom field. When I disabled the extension I was able to create custom fields again.

CiviCRM 4.7.15
Wordpress Version 4.7.2

Screencast showing the steps I took to create the issue: https://www.youtube.com/watch?v=asjSQVBG2eU

ERROR REPORT FROM CONSOLE
==============================
CiviCRM_API3_Exception: "id is not a valid integer"

#0
/home/vandergiessen/www/www/wp-content/plugins/files/civicrm/custom_ext/org.civicoop.civir
ules/CRM/Civirules/Utils/CustomField.php(25): civicrm_api3("CustomField", "getsingle",
(Array:1))
#1
/home/vandergiessen/www/www/wp-content/plugins/files/civicrm/custom_ext/org.civicoop.civir
ules/CRM/Civirules/Utils/CustomDataFromPre.php(40):
CRM_Civirules_Utils_CustomField::isCustomFieldMultiselect("group")
#2
/home/vandergiessen/www/www/wp-content/plugins/files/civicrm/custom_ext/org.civicoop.civir
ules/CRM/Civirules/Utils/CustomDataFromPre.php(22):
CRM_Civirules_Utils_CustomDataFromPre::setCustomData("CustomField", "group", "1", "id")
#3
/home/vandergiessen/www/www/wp-content/plugins/files/civicrm/custom_ext/org.civicoop.civir
ules/civirules.php(133): CRM_Civirules_Utils_CustomDataFromPre::pre("create",
"CustomField", NULL, (Array:34))
#4 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(236):
civirules_civicrm_pre("create", "CustomField", NULL, (Array:34))
#5
/home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.ph
p(156): CRM_Utils_Hook->runHooks((Array:9), "civicrm_pre", 4, "create", "CustomField",
NULL, (Array:34), NULL, NULL)
#6 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(301):
CRM_Utils_Hook_WordPress->invoke(4, "create", "CustomField", NULL, (Array:34), NULL, NULL,
"civicrm_pre")
#7
/home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomField.ph
p(136): CRM_Utils_Hook::pre("create", "CustomField", NULL, (Array:34))
#8
/home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Custom/Form/Field.php
(1000): CRM_Core_BAO_CustomField::create((Array:34))
#9 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(435):
CRM_Custom_Form_Field->postProcess()
#10
/home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/D
one.php(75): CRM_Core_Form->mainProcess()
#11
/home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Con
troller.php(203): CRM_Core_QuickForm_Action_Done->perform(Object(CRM_Custom_Form_Field),
"done")
#12
/home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Pag
e.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Custom_Form_Field), "done")
#13 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php
(351): HTML_QuickForm_Page->handle("done")
#14 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php
(113): CRM_Core_Controller->run()
#15 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php
(284): CRM_Utils_Wrapper->run("CRM_Custom_Form_Field", "Custom Field - Add", NULL)
#16 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php
(84): CRM_Core_Invoke::runItem((Array:13))
#17 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php
(52): CRM_Core_Invoke::_invoke((Array:6))
#18 /home/vandergiessen/www/www/wp-content/plugins/civicrm/civicrm.php(1227):
CRM_Core_Invoke::invoke((Array:6))
#19 [internal function](): CiviCRM_For_WordPress->invoke("")
#20 /home/vandergiessen/www/www/wp-includes/class-wp-hook.php(298): call_user_func_array(
(Array:2), (Array:1))
#21 /home/vandergiessen/www/www/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters
("", (Array:1))
#22 /home/vandergiessen/www/www/wp-includes/plugin.php(453): WP_Hook->do_action((Array:1))

#23 /home/vandergiessen/www/www/wp-admin/admin.php(222): do_action
("toplevel_page_CiviCRM")
#24 {main}

Sorry but we are not able to provide this at the moment.
id is not a valid integer
==============================

**Comment by yosefromano** [comment] 2017-02-06 22:35
I have the same issue on Civi 4.6.25 + Drupal 7

**Comment by jaapjansma** [comment] 2017-02-07 07:49
@yosefromano @elijahv Thanks for reporting the latest version of CiviRules is version 1.11 could you check whether the bug still exists in this version?

**Comment by yosefromano** [comment] 2017-02-07 20:36
@jaapjansma upgrading to Version 1.11 got rid of the bug however it also got rid of all my existing rules. Any work arounds?

**Comment by jaapjansma** [comment] 2017-02-08 08:03
@yosefromano not really this is probably caused by the fact that we renamed Event to Trigger. Probably the best solution is to setup the rules again manually.

**Comment by jaapjansma** [comment] 2018-06-12 12:23
I assume that the error in this issue is gone and will therefor close the issue.

**Closed** 2018-06-12 12:42 UTC
